travis:
  secure:
    BINSTAR_TOKEN: D54kn4FngXE9COVooVL4vTFDbAG9AuN789FKUz89BhTRQ0C3vs07Gr3WuBYiCJX87R/atSAFG1QQ2tj765TmlvPS/zJ28RvXO+LZuU4Sz5VjIzn0QFoNV7L/cSjEyS1YLHwod0J/jpJoymPX2j35PLC+UtswRGaO6R5Q5Opkgxb3vu7oXE159K2POPHgAYjbwRV9G/oZK9NSzc78oVO9U6Uts5W8f6jbC6T4PHJWsWnkCvqH3zOMW2ZFCIcAx+O0ZUicQH1HUJoY1T+BIWlAwnIBn5VtPX8gnn1FFw+pk59Q2BaVOb+K+LGwcJ1KN8oICCcu6wB3Y9g2NYilIADdEG/4zPcV0+fPh7tfIMk3cIFeNlf3QeBf9Jxs+00+umaXzLF7PEs+Yz2Py8bbFVsCdxORp+dw0XUJGs6kb/uiSRReAFplPlx3ch3O4U6sP4E0tu05f9PVTQXT93SfdqQmLdOuhzCYICpk4zZfAaRnZmT41BmjMJYeTaTbhRGpGVjcJdxfUA0a3Gx/BmufyvuS90t7dFaI0d48lAQEAYy3qEhODpLIx9OFPMcUGQo5LENX7knPK5E5VwADVTGiqfHo9i1bdob0nRHgp/B1zXOn0joTulnxzX1Jk1CrEdQIlkFxyBLv1ikBkQ48h6T6Btxd/Gw4I9NKZJJekBA00qEGC7A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
