appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Ig14OqQLz5qCvuwcn5yJMdb2p/CJzXQw5GxJXVRAn7+cxe3ODC0+mLtjE2/KfO856XGxooseWM/Q5WlmlJvFzE09TOnZsxHRehHJgl/6GpkbOK4LnOM4NwahF3hfHR5qHLCkb58xJY/as6Ir3bIRIgX0GeKMAPK9DdOQdHjTtJVkwHA6JMQjbeiUR43YvzL8iXOAEgtDr+xuhMir+Zcu9mqwsulAd905A9R1adxB18cMNec4UMZLwHTQ/4W4p8/Ezvd8Z2JvFHX8N9clDZ61kFPMTwkgASOWoe2dT5ffnSpFdEXWicuQRhQXi3+NS1eGuHY97zT2Y3H1iNffjpZ5Mg9NxST04I23hyrAtTdkMl6lNRklqGVa0dksKMo57RVm8d/sOWKGOBZ8sZO4rBx8ngLmm54sHH5YoMfTXZwx8HIVnT2UTpo/TM3YfTiO2Z2ptZ4+Fujvg93qXrg4GrayiWoc8MJqSQPdw75Dsw6fytU/at3fy3c/Zm0FvYqLPxx91agYyqY1K1ePFENcVE0MGN+7GLqWLvPhgA1pNLGfSZU8pQl+gOsaNLmiWGLPvYcnCoq+WsW6zjBPs4avejU7dMZMjOVkSCLCC2LkV0H4Wi/iGtSx9QsxHKmPNMDaZu4iIBNb0yOJZxsTLd1fkIIya3Qk4TYNZbe7AS7gvPXaFGw=}
conda_forge_output_validation: true
